---
title: "Working with United States Census Data Using tidycensus"
output: html_document
---


```{r, echo=FALSE,results=FALSE,message=FALSE}
library(tidycensus)
library(tidyverse)
library(knitr)
Sys.getenv("CENSUS_API_KEY")
```

```{r, eval=FALSE}
library(tidycensus)
library(tidyverse)
census_api_key("YOUR API KEY GOES HERE")
```

## Inspect variables for Decennial Census
```{r view variables}
decennial_variables<-load_variables(2010,"sf1")
View(decennial_variables)
```

```{r,echo=FALSE}
kable(head(decennial_variables))
```


## 
```{r, message=FALSE}
state_population_2010<-get_decennial(geography = "state", 
                                                  variables = "P001001", 
                                                  year = 2010)
View(state_population_2010)
```


```{r,echo=FALSE}
kable(head(state_population_2010))
```






## Appendix 

```{r}
my_years<-c(2000,2010)
population_rural_2000_2010<-map(
  my_years,
  ~(get_decennial(geography = "state", 
                 variables = c("P001001", "P002005"),
                 output="wide",
                 year =.)) %>% 
      mutate(rural_pct=(P002005/P001001)*100) %>% 
      arrange(NAME)
  )

names(population_rural_2000_2010)<-my_years

joined_ds<-full_join(population_rural_2000_2010[["2000"]],population_rural_2000_2010[["2010"]],by="NAME") %>% 
           mutate(pct_change=rural_pct.y-rural_pct.x) %>% 
           select(NAME,pct_change)
joined_ds
```

