---
title: "Census Data in R"
author: "Aditya Ranganath"
date: "2/17/2022"
output:
  html_document:
        toc: true
        toc_depth: 3
        toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preliminaries: Load Libraries

```{r, message=F, results=F, warning=F}
library(tidycensus)
library(tidyverse)
library(sf)
library(tmap)
```

# Census Data Extraction: Basics

## Extracting a table of variable codes

```{r}
# Calls up variable codes from 2010 decennial census and assigns to object named "decennial_variables"
decennial_variables<-load_variables(2010,"sf1")
```

```{r}
# Prints contents of "decennial_variables"
decennial_variables
```

## Extracting data with ```get_decennial``` 

### Example 1

```{r, message=F, warning=F, results=F}
# Generate a table of population by state, based on the 2010 decennial census
state_population_2010<-get_decennial(geography = "state", 
                                     variables = "P001001", 
                                     geometry=TRUE,
                                     year = 2010)
```

```{r}
# prints "state_population_2010"
state_population_2010
```

### Example 2

```{r, results=FALSE, warning=FALSE, message=FALSE}
# Generate a table of the population distribution across Colorado counties in the year 2010, based on the 2010 decennial census

CO_county_population_2010<-get_decennial(geography = "county", 
                                         state="CO",
                                         variables = "P001001", 
                                         year = 2010)
```

```{r}
# Prints "CO_county_population_2010"
CO_county_population_2010
```

## Cleaning Extracted Data

```{r}
# Clean up the table of CO population by county by removing the "variable" column, and renaming the "value" column as "Population", which we can do using the tidyverse's "dplyr" package

CO_county_population_2010<-CO_county_population_2010 %>% 
                           mutate(variable=NULL) %>% 
                           rename(population=value)

```

```{r}
# prints updated contents of "CO_county_population_2010"
CO_county_population_2010
```

## Extracting Multiple Census Variables

```{r}
# Create a new object containing a dataset of rural population AND overall population by state,based on the 2010 decennial. Also, renames the variables, and arrange the dataset in descending order with respect to the rural population

state_pop_ruralpop_2010<-get_decennial(geography = "state", 
                                       variables = c("P001001", "P002005"),
                                       output="wide",
                                       year = 2010) %>% 
                          rename(total_population=P001001, rural_population=P002005) %>% 
                          arrange(desc(rural_population))
```


```{r}
# prints contents of "state_pop_ruralpop_2010"
state_pop_ruralpop_2010
```

## Creating New Variables

```{r}
#Using dplyr, generate a new variable in the dataset based on existing variables; 
# in particular, create a variable called "rural_pct" that reflects the rural population 
# as a percentage of the population, and then arranges it in descrend order
# with respect to the new "rural_pct" variable

state_pop_ruralpop_2010<- state_pop_ruralpop_2010 %>% 
                            mutate(rural_pct=(rural_population/total_population)*100) %>% 
                            arrange(desc(rural_pct))

```

```{r}
# prints "state_pop_ruralpop_2010"
state_pop_ruralpop_2010
```

## Filtering census datasets

```{r}
# Extracts observations from "state_pop_ruralpop_2010" where rural_pct>40 and assigns to a new object named "rural_pct_over40"

rural_pct_over40<-state_pop_ruralpop_2010 %>%
                  filter(rural_pct>40)
```

```{r}
rural_pct_over40
```



